### ISSUE TITLE
mysql install fails, because of GPG failures

### ISSUE THREAD

**Issue by daften** [chef-cookbooks/yum-mysql-community#16]
### Cookbook version
2.1.0

### Chef-client version
13.4.24

### Platform Details
Centos 7.4

### Scenario:
Install mysql 5.7

### Steps to Reproduce:
Just use the default installation as indicated in README

### Expected Result:
MySQL installed

### Actual Result:
```
STDOUT: Public key for mysql-community-common-5.7.21-1.el7.x86_64.rpm is not installed
STDERR: warning: /var/cache/yum/x86_64/7/mysql57-community/packages/mysql-community-common-5.7.21-1.el7.x86_64.rpm: Header V3 DSA/SHA1 Signature, key ID 5072e1f5: NOKEY
GPG key retrieval failed: [Errno 14] HTTPS Error 404 - Not Found
```

**Comment by fjsrn** [comment]
Same here, it seems like this is not a thing anymore:
'https://raw.githubusercontent.com/rs-services/equinix-public/master/cookbooks/db_mysql/files/centos/mysql_pubkey.asc'

**Comment by TheKatarGit** [comment]
@daften @fjsrn https://github.com/chef-cookbooks/yum-mysql-community/pull/17

**Comment by dschlenk** [comment]
For those using an older release, you can work around this by setting this node attribute in a wrapper/role/environment:
```
    "yum": {
      "mysql57-community": {
        "gpgkey": "https://raw.githubusercontent.com/chef-cookbooks/yum-mysql-community/master/files/mysql_pubkey.asc"
      }
    }
```

Tho IMO maybe referencing a raw GitHub content URL is worse than defining the key as a file or node attribute and referencing it on the local filesystem? Happy to provide a patch for that if there's consensus on that.

**Comment by suicide** [comment]
how about using the official key location?
https://repo.mysql.com/RPM-GPG-KEY-mysql

**Comment by dschlenk** [comment]
@suicide at first glance the files do not appear to be equal

**Comment by suicide** [comment]
@dschlenk someone on the mysql bugtracker pointed me to it. it seems to be same as in the documentation: https://dev.mysql.com/doc/refman/5.7/en/checking-gpg-signature.html

**Comment by kumbsatyam** [comment]
@dschlenk, trying to implement the work around you suggested earlier, ( by setting node attribute in a wrapper/role/environment), Am very much a beginner in this area, can you please let me know where exactly please? thanks

**Comment by dschlenk** [comment]
@kumbsatyam sure, tell me about your setup - are you using a wrapper cookbook, using chef in server or solo mode, etc?

The example I posted is JSON so would be most useful in the default or override attributes section of a role or environment file.

**Comment by kumbsatyam** [comment]
@dschlenk, thanks for the response.  Am using chef in server, and using default installation, and using recipe mysql.rb to install mysql56-community.  The issue is GPG Key retrial fails when it tries to hit ==> 

gpgkey=https://raw.githubusercontent.com/chef-cookbooks/yum-mysql-community/master/files/default/mysql_pubkey.asc
where
https://raw.githubusercontent.com/chef-cookbooks/yum-mysql-community/master/files/mysql_pubkey.asc

works when I try to install mysql manually with yum.  

Please help.  

Thanks in advance.

**Comment by dschlenk** [comment]
@kumbsatyam okay, so did you apply the recipe to your node's run list directly, or did you add it to a role and assign that role to the node?

**Comment by walkerab** [comment]
@dschlenk Thank you! Your fix works for mysql55-community also!

**Comment by kumbsatyam** [comment]
@dschlenk applied the recipe to node's run list directly.

**Comment by dschlenk** [comment]
@kumbsatyam in that case it's probably easiest to edit your environment

```
knife environment edit <environment name>
```
then, add the snippet to the `default_attributes` section.

**Comment by kumbsatyam** [comment]
@dschlenk, adding the following to mysql.rb
yum_repository 'mysql56-community' do
	baseurl 'http://repo.mysql.com/yum/mysql-5.6-community/el/$releasever/$basearch/'
	enabled true
	failovermethod 'priority'
	gpgcheck true
	gpgkey 'https://raw.githubusercontent.com/chef-cookbooks/yum-mysql-community/master/files/mysql_pubkey.asc'
end
has fixed this issue!  

Thanks for all your help David.

**Comment by eyespies** [comment]
There has to be a better way to do this than hosting the file on GitHub. This broke a bunch of stuff for us as well and now there is a firedrill to fix it. Improving the code for one group shouldn't break the code for the rest of us and require a fire drill to fix.

What other options are there for retrieving the GPG files?

**Comment by eyespies** [comment]
As an aside - the suggestion for using the MySQL provided key is probably best. @tas50 mentioned that it is different, however on the surface there is a good reason for that - the key shows a timestamp of 21-Feb-2018, which would mean the key hosted in this cookbook is no longer valid:
```
[FILE] RPM-GPG-KEY-mysql                 21-Feb-2017 02:36    27k  
```

It looks like they also changed the key length since the new key is much longer. @tas50 any chance you would reconsider the use of https://repo.mysql.com/RPM-GPG-KEY-mysql as the source?

**Comment by dschlenk** [comment]
@eyespies if you're using a wrapper you could also modify the resource to point at a self hosted URL. Something like:
```
begin
  repo = resources('yum_repository[mysql57-community]')
  repo.gpgkey = <INTERNAL_URL>
rescue StandardError
  Chef::Log.warn "Unable to modify gpgkey location of mysql community repo - is it in your run list?"
end
```

**Comment by eyespies** [comment]
@dschlenk - yes I could, but to me there is a bigger issue and that is moving files around shouldn't break a cookbook for others. It should be limited in scope to the new version, so if I don't upgrade, my cookbook should still work. With the current setup of this file in the cookbook, that is not true - it is possible to introduce breaking changes for *all versions*. And that is just what happened here. To me that is not an appropriate setup.

If we can use the MySQL provided version as @suicide suggested, I would hope things shouldn't break - if they change the key, they have to regenerate all the signatures. (Yes, I admit they could still break things on us too...)

**Comment by eyespies** [comment]
I just ran a test and the MySQL GPG works fine so I second the request from @suicide 

```Total size: 82 M
Downloading packages:
warning: /var/cache/yum/x86_64/7/mysql56-community/packages/mysql-community-server-5.6.39-2.el7.x86_64.rpm: Header V3 DSA/SHA1 Signature, key ID 5072e1f5: NOKEY
Retrieving key from https://repo.mysql.com/RPM-GPG-KEY-mysql
Importing GPG key 0x5072E1F5:
 Userid     : "MySQL Release Engineering <mysql-build@oss.oracle.com>"
 Fingerprint: a4a9 4068 76fc bd3c 4567 70c8 8c71 8d3b 5072 e1f5
 From       : https://repo.mysql.com/RPM-GPG-KEY-mysql
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : perl-Data-Dumper-2.145-3.el7.x86_64 
...
```

**Comment by dschlenk** [comment]
@eyespies agree, which is why I offered to write a patch to include the file in the cookbook itself. (I haven't written anything yet due to spacetime limits and lack of clarity on which key should be used for that). Just making sure you know your options for workaround.

**Comment by eyespies** [comment]
Thank you @dschlenk - appreciate the help. I second sourcing the file from MySQL though, rather than including it in the cookbook.

**Comment by eyespies** [comment]
I'll try to run some tests this weekend to confirm that the MySQL GPG key works for all versions (5.5, 5.6, etc) to be safe and will submit a PR if it does.

**Comment by eyespies** [comment]
@tas50 kindly merged the PR I submitted, however it only helps future versions of this cookbook and not the previously broken versions, so this issue is still valid for anyone not on 4.0.0 or higher.

The only fixes are:
- use the workaround suggested by @dschlenk 
- upgrade to 4.0.0 or higher
- fork the cookbook and put the file back where it was for your own use
- put the file back to files/default (but I think this option won't be pursued)

**Comment by bigplants** [comment]
Hi, 
I fixed the error in older version with #22 
This is very simple solution. Only reverted old path of gpgkey.
My changes look dirty. However, I think this is a good way.
Because, all versions excluding latest refer gpgkey file in **master** branch..
I don't have any other idea without side effect.

**Comment by tas50** [comment]
Should be fixed now w/o the upgrade of the cookbook

**Comment by amolpali** [comment]
> how about using the official key location?
> https://repo.mysql.com/RPM-GPG-KEY-mysql

Perfect this works. Just run below commands.
cd /etc/pki/rpm-gpg/
wget https://repo.mysql.com/RPM-GPG-KEY-mysql
yum install mysql-community-server

**Comment by RaitKivinurm** [comment]
> /etc/pki/rpm-gpg/

oneliner 
wget -P /etc/pki/rpm-gpg/ https://repo.mysql.com/RPM-GPG-KEY-mysql && yum install mysql-community-server

**Comment by RaitKivinurm** [comment]
need to use in Dockerfile cant find the way
best I could come up to was:
```
RUN mkdir -p /etc/pki/rpm-gpg/
RUN wget -P /etc/pki/rpm-gpg/ https://repo.mysql.com/RPM-GPG-KEY-mysql 
RUN yum install -y \
    https://repo.mysql.com/mysql-cluster-community-minimal-release-el7.rpm \
    https://repo.mysql.com/mysql-community-release-el7.rpm 
```
but that also not working still getting error:
```
#9 1.201 Transaction check error:
#9 1.201   file /etc/pki/rpm-gpg/RPM-GPG-KEY-mysql conflicts between attempted installs of mysql-cluster-community-minimal-release-el7-1.noarch and mysql80-community-release-el7-3.noarch
```

any idea?
thanks

**Comment by valerio-bozzolan** [comment]
Sorry if I comment on this old post but I recommend a backup first:

```
cd /etc/pki/rpm-gpg/
mv RPM-GPG-KEY-mysql RPM-GPG-KEY-mysql.bak
wget https://repo.mysql.com/RPM-GPG-KEY-mysql
```

To then retry:

```
yum install mysql-community-server
```

If it still does not work, try manually copying it from there:

https://dev.mysql.com/doc/refman/8.0/en/gpg-key-archived-packages.html
